[project]
name = "presentation-as-code-app"
version = "0.1.0"
description = "Presentation as code demo AI app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.64.0",
    "python-dotenv>=1.0.1",
    "streamlit>=1.42.2",
]
